version: '1'
services:
  uni-tasks-go:
    depends_on:
      - uni-tasks-roach
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: uni-tasks-rest-server
    hostname: rest-server
    networks:
      - uni-tasks-net
    ports:
      - 8080:8080
    deploy:
        restart_policy:
          condition: on-failure
  uni-tasks-roach:
    image: cockroachdb/cockroach:latest-v20.1
    container_name: uni-tasks-roach
    hostname: db
    networks:
      - uni-tasks-net
    ports:
      - 26257:26257
      - 8081:8080
    volumes:
      - uni-tasks-1:/cockroach/cockroach-data
    command: start-single-node --insecure
    deploy:
        restart_policy:
          condition: on-failure
volumes:
  uni-tasks-1:

networks:
  uni-tasks-net:
    driver: bridge